/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/_checkout'
import { Route as CountryCodeMainRouteImport } from './routes/$countryCode/_main'
import { Route as CountryCodeCheckoutCheckoutRouteImport } from './routes/$countryCode/_checkout/checkout'
import { Route as CountryCodeMainIndexRouteImport } from './routes/$countryCode/_main/index'
import { Route as CountryCodeMainAccountRouteImport } from './routes/$countryCode/_main/account'
import { Route as CountryCodeMainCartRouteImport } from './routes/$countryCode/_main/cart'
import { Route as CountryCodeMainStoreRouteImport } from './routes/$countryCode/_main/store'
import { Route as CountryCodeMainVerifyAccountRouteImport } from './routes/$countryCode/_main/verify-account'
import { Route as CountryCodeMainAccountIndexRouteImport } from './routes/$countryCode/_main/account/index'
import { Route as CountryCodeMainAccountAddressesRouteImport } from './routes/$countryCode/_main/account/addresses'
import { Route as CountryCodeMainAccountOrdersRouteImport } from './routes/$countryCode/_main/account/orders'
import { Route as CountryCodeMainAccountProfileRouteImport } from './routes/$countryCode/_main/account/profile'
import { Route as CountryCodeMainCategoriesSplatRouteImport } from './routes/$countryCode/_main/categories.$'
import { Route as CountryCodeMainCollectionsHandleRouteImport } from './routes/$countryCode/_main/collections/$handle'
import { Route as CountryCodeMainProductsHandleRouteImport } from './routes/$countryCode/_main/products/$handle'
import { Route as CountryCodeMainOrderIdConfirmedRouteImport } from './routes/$countryCode/_main/order/$id/confirmed'
import { Route as CountryCodeMainAccountOrdersDetailsIdRouteImport } from './routes/$countryCode/_main/account/orders/details/$id'
import { Route as CountryCodeMainOrderIdTransferTokenRouteImport } from './routes/$countryCode/_main/order/$id/transfer/$token'
import { Route as CountryCodeMainOrderIdTransferTokenIndexRouteImport } from './routes/$countryCode/_main/order/$id/transfer/$token/index'
import { Route as CountryCodeMainOrderIdTransferTokenAcceptRouteImport } from './routes/$countryCode/_main/order/$id/transfer/$token/accept'
import { Route as CountryCodeMainOrderIdTransferTokenDeclineRouteImport } from './routes/$countryCode/_main/order/$id/transfer/$token/decline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/_checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeMainRoute = CountryCodeMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutCheckoutRoute =
  CountryCodeCheckoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => CountryCodeCheckoutRoute,
  } as any)
const CountryCodeMainIndexRoute = CountryCodeMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeMainRoute,
} as any)
const CountryCodeMainAccountRoute = CountryCodeMainAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CountryCodeMainRoute,
} as any)
const CountryCodeMainCartRoute = CountryCodeMainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeMainRoute,
} as any)
const CountryCodeMainStoreRoute = CountryCodeMainStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeMainRoute,
} as any)
const CountryCodeMainVerifyAccountRoute =
  CountryCodeMainVerifyAccountRouteImport.update({
    id: '/verify-account',
    path: '/verify-account',
    getParentRoute: () => CountryCodeMainRoute,
  } as any)
const CountryCodeMainAccountIndexRoute =
  CountryCodeMainAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryCodeMainAccountRoute,
  } as any)
const CountryCodeMainAccountAddressesRoute =
  CountryCodeMainAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => CountryCodeMainAccountRoute,
  } as any)
const CountryCodeMainAccountOrdersRoute =
  CountryCodeMainAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => CountryCodeMainAccountRoute,
  } as any)
const CountryCodeMainAccountProfileRoute =
  CountryCodeMainAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => CountryCodeMainAccountRoute,
  } as any)
const CountryCodeMainCategoriesSplatRoute =
  CountryCodeMainCategoriesSplatRouteImport.update({
    id: '/categories/$',
    path: '/categories/$',
    getParentRoute: () => CountryCodeMainRoute,
  } as any)
const CountryCodeMainCollectionsHandleRoute =
  CountryCodeMainCollectionsHandleRouteImport.update({
    id: '/collections/$handle',
    path: '/collections/$handle',
    getParentRoute: () => CountryCodeMainRoute,
  } as any)
const CountryCodeMainProductsHandleRoute =
  CountryCodeMainProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeMainRoute,
  } as any)
const CountryCodeMainOrderIdConfirmedRoute =
  CountryCodeMainOrderIdConfirmedRouteImport.update({
    id: '/order/$id/confirmed',
    path: '/order/$id/confirmed',
    getParentRoute: () => CountryCodeMainRoute,
  } as any)
const CountryCodeMainAccountOrdersDetailsIdRoute =
  CountryCodeMainAccountOrdersDetailsIdRouteImport.update({
    id: '/details/$id',
    path: '/details/$id',
    getParentRoute: () => CountryCodeMainAccountOrdersRoute,
  } as any)
const CountryCodeMainOrderIdTransferTokenRoute =
  CountryCodeMainOrderIdTransferTokenRouteImport.update({
    id: '/order/$id/transfer/$token',
    path: '/order/$id/transfer/$token',
    getParentRoute: () => CountryCodeMainRoute,
  } as any)
const CountryCodeMainOrderIdTransferTokenIndexRoute =
  CountryCodeMainOrderIdTransferTokenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CountryCodeMainOrderIdTransferTokenRoute,
  } as any)
const CountryCodeMainOrderIdTransferTokenAcceptRoute =
  CountryCodeMainOrderIdTransferTokenAcceptRouteImport.update({
    id: '/accept',
    path: '/accept',
    getParentRoute: () => CountryCodeMainOrderIdTransferTokenRoute,
  } as any)
const CountryCodeMainOrderIdTransferTokenDeclineRoute =
  CountryCodeMainOrderIdTransferTokenDeclineRouteImport.update({
    id: '/decline',
    path: '/decline',
    getParentRoute: () => CountryCodeMainOrderIdTransferTokenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/$countryCode/checkout': typeof CountryCodeCheckoutCheckoutRoute
  '/$countryCode/account': typeof CountryCodeMainAccountRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeMainCartRoute
  '/$countryCode/store': typeof CountryCodeMainStoreRoute
  '/$countryCode/verify-account': typeof CountryCodeMainVerifyAccountRoute
  '/$countryCode/': typeof CountryCodeMainIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeMainAccountAddressesRoute
  '/$countryCode/account/orders': typeof CountryCodeMainAccountOrdersRouteWithChildren
  '/$countryCode/account/profile': typeof CountryCodeMainAccountProfileRoute
  '/$countryCode/categories/$': typeof CountryCodeMainCategoriesSplatRoute
  '/$countryCode/collections/$handle': typeof CountryCodeMainCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeMainProductsHandleRoute
  '/$countryCode/account/': typeof CountryCodeMainAccountIndexRoute
  '/$countryCode/order/$id/confirmed': typeof CountryCodeMainOrderIdConfirmedRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeMainAccountOrdersDetailsIdRoute
  '/$countryCode/order/$id/transfer/$token': typeof CountryCodeMainOrderIdTransferTokenRouteWithChildren
  '/$countryCode/order/$id/transfer/$token/accept': typeof CountryCodeMainOrderIdTransferTokenAcceptRoute
  '/$countryCode/order/$id/transfer/$token/decline': typeof CountryCodeMainOrderIdTransferTokenDeclineRoute
  '/$countryCode/order/$id/transfer/$token/': typeof CountryCodeMainOrderIdTransferTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeMainIndexRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutCheckoutRoute
  '/$countryCode/cart': typeof CountryCodeMainCartRoute
  '/$countryCode/store': typeof CountryCodeMainStoreRoute
  '/$countryCode/verify-account': typeof CountryCodeMainVerifyAccountRoute
  '/$countryCode/account/addresses': typeof CountryCodeMainAccountAddressesRoute
  '/$countryCode/account/orders': typeof CountryCodeMainAccountOrdersRouteWithChildren
  '/$countryCode/account/profile': typeof CountryCodeMainAccountProfileRoute
  '/$countryCode/categories/$': typeof CountryCodeMainCategoriesSplatRoute
  '/$countryCode/collections/$handle': typeof CountryCodeMainCollectionsHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeMainProductsHandleRoute
  '/$countryCode/account': typeof CountryCodeMainAccountIndexRoute
  '/$countryCode/order/$id/confirmed': typeof CountryCodeMainOrderIdConfirmedRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeMainAccountOrdersDetailsIdRoute
  '/$countryCode/order/$id/transfer/$token/accept': typeof CountryCodeMainOrderIdTransferTokenAcceptRoute
  '/$countryCode/order/$id/transfer/$token/decline': typeof CountryCodeMainOrderIdTransferTokenDeclineRoute
  '/$countryCode/order/$id/transfer/$token': typeof CountryCodeMainOrderIdTransferTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/$countryCode/_checkout': typeof CountryCodeCheckoutRouteWithChildren
  '/$countryCode/_main': typeof CountryCodeMainRouteWithChildren
  '/$countryCode/_checkout/checkout': typeof CountryCodeCheckoutCheckoutRoute
  '/$countryCode/_main/account': typeof CountryCodeMainAccountRouteWithChildren
  '/$countryCode/_main/cart': typeof CountryCodeMainCartRoute
  '/$countryCode/_main/store': typeof CountryCodeMainStoreRoute
  '/$countryCode/_main/verify-account': typeof CountryCodeMainVerifyAccountRoute
  '/$countryCode/_main/': typeof CountryCodeMainIndexRoute
  '/$countryCode/_main/account/addresses': typeof CountryCodeMainAccountAddressesRoute
  '/$countryCode/_main/account/orders': typeof CountryCodeMainAccountOrdersRouteWithChildren
  '/$countryCode/_main/account/profile': typeof CountryCodeMainAccountProfileRoute
  '/$countryCode/_main/categories/$': typeof CountryCodeMainCategoriesSplatRoute
  '/$countryCode/_main/collections/$handle': typeof CountryCodeMainCollectionsHandleRoute
  '/$countryCode/_main/products/$handle': typeof CountryCodeMainProductsHandleRoute
  '/$countryCode/_main/account/': typeof CountryCodeMainAccountIndexRoute
  '/$countryCode/_main/order/$id/confirmed': typeof CountryCodeMainOrderIdConfirmedRoute
  '/$countryCode/_main/account/orders/details/$id': typeof CountryCodeMainAccountOrdersDetailsIdRoute
  '/$countryCode/_main/order/$id/transfer/$token': typeof CountryCodeMainOrderIdTransferTokenRouteWithChildren
  '/$countryCode/_main/order/$id/transfer/$token/accept': typeof CountryCodeMainOrderIdTransferTokenAcceptRoute
  '/$countryCode/_main/order/$id/transfer/$token/decline': typeof CountryCodeMainOrderIdTransferTokenDeclineRoute
  '/$countryCode/_main/order/$id/transfer/$token/': typeof CountryCodeMainOrderIdTransferTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$countryCode'
    | '/$countryCode/checkout'
    | '/$countryCode/account'
    | '/$countryCode/cart'
    | '/$countryCode/store'
    | '/$countryCode/verify-account'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/order/$id/confirmed'
    | '/$countryCode/account/orders/details/$id'
    | '/$countryCode/order/$id/transfer/$token'
    | '/$countryCode/order/$id/transfer/$token/accept'
    | '/$countryCode/order/$id/transfer/$token/decline'
    | '/$countryCode/order/$id/transfer/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$countryCode'
    | '/$countryCode/checkout'
    | '/$countryCode/cart'
    | '/$countryCode/store'
    | '/$countryCode/verify-account'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$'
    | '/$countryCode/collections/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account'
    | '/$countryCode/order/$id/confirmed'
    | '/$countryCode/account/orders/details/$id'
    | '/$countryCode/order/$id/transfer/$token/accept'
    | '/$countryCode/order/$id/transfer/$token/decline'
    | '/$countryCode/order/$id/transfer/$token'
  id:
    | '__root__'
    | '/'
    | '/$countryCode'
    | '/$countryCode/_checkout'
    | '/$countryCode/_main'
    | '/$countryCode/_checkout/checkout'
    | '/$countryCode/_main/account'
    | '/$countryCode/_main/cart'
    | '/$countryCode/_main/store'
    | '/$countryCode/_main/verify-account'
    | '/$countryCode/_main/'
    | '/$countryCode/_main/account/addresses'
    | '/$countryCode/_main/account/orders'
    | '/$countryCode/_main/account/profile'
    | '/$countryCode/_main/categories/$'
    | '/$countryCode/_main/collections/$handle'
    | '/$countryCode/_main/products/$handle'
    | '/$countryCode/_main/account/'
    | '/$countryCode/_main/order/$id/confirmed'
    | '/$countryCode/_main/account/orders/details/$id'
    | '/$countryCode/_main/order/$id/transfer/$token'
    | '/$countryCode/_main/order/$id/transfer/$token/accept'
    | '/$countryCode/_main/order/$id/transfer/$token/decline'
    | '/$countryCode/_main/order/$id/transfer/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/_checkout': {
      id: '/$countryCode/_checkout'
      path: ''
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/_main': {
      id: '/$countryCode/_main'
      path: ''
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeMainRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/_checkout/checkout': {
      id: '/$countryCode/_checkout/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutCheckoutRouteImport
      parentRoute: typeof CountryCodeCheckoutRoute
    }
    '/$countryCode/_main/': {
      id: '/$countryCode/_main/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeMainIndexRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/account': {
      id: '/$countryCode/_main/account'
      path: '/account'
      fullPath: '/$countryCode/account'
      preLoaderRoute: typeof CountryCodeMainAccountRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/cart': {
      id: '/$countryCode/_main/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeMainCartRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/store': {
      id: '/$countryCode/_main/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeMainStoreRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/verify-account': {
      id: '/$countryCode/_main/verify-account'
      path: '/verify-account'
      fullPath: '/$countryCode/verify-account'
      preLoaderRoute: typeof CountryCodeMainVerifyAccountRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/account/': {
      id: '/$countryCode/_main/account/'
      path: '/'
      fullPath: '/$countryCode/account/'
      preLoaderRoute: typeof CountryCodeMainAccountIndexRouteImport
      parentRoute: typeof CountryCodeMainAccountRoute
    }
    '/$countryCode/_main/account/addresses': {
      id: '/$countryCode/_main/account/addresses'
      path: '/addresses'
      fullPath: '/$countryCode/account/addresses'
      preLoaderRoute: typeof CountryCodeMainAccountAddressesRouteImport
      parentRoute: typeof CountryCodeMainAccountRoute
    }
    '/$countryCode/_main/account/orders': {
      id: '/$countryCode/_main/account/orders'
      path: '/orders'
      fullPath: '/$countryCode/account/orders'
      preLoaderRoute: typeof CountryCodeMainAccountOrdersRouteImport
      parentRoute: typeof CountryCodeMainAccountRoute
    }
    '/$countryCode/_main/account/profile': {
      id: '/$countryCode/_main/account/profile'
      path: '/profile'
      fullPath: '/$countryCode/account/profile'
      preLoaderRoute: typeof CountryCodeMainAccountProfileRouteImport
      parentRoute: typeof CountryCodeMainAccountRoute
    }
    '/$countryCode/_main/categories/$': {
      id: '/$countryCode/_main/categories/$'
      path: '/categories/$'
      fullPath: '/$countryCode/categories/$'
      preLoaderRoute: typeof CountryCodeMainCategoriesSplatRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/collections/$handle': {
      id: '/$countryCode/_main/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/$countryCode/collections/$handle'
      preLoaderRoute: typeof CountryCodeMainCollectionsHandleRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/products/$handle': {
      id: '/$countryCode/_main/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeMainProductsHandleRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/order/$id/confirmed': {
      id: '/$countryCode/_main/order/$id/confirmed'
      path: '/order/$id/confirmed'
      fullPath: '/$countryCode/order/$id/confirmed'
      preLoaderRoute: typeof CountryCodeMainOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/account/orders/details/$id': {
      id: '/$countryCode/_main/account/orders/details/$id'
      path: '/details/$id'
      fullPath: '/$countryCode/account/orders/details/$id'
      preLoaderRoute: typeof CountryCodeMainAccountOrdersDetailsIdRouteImport
      parentRoute: typeof CountryCodeMainAccountOrdersRoute
    }
    '/$countryCode/_main/order/$id/transfer/$token': {
      id: '/$countryCode/_main/order/$id/transfer/$token'
      path: '/order/$id/transfer/$token'
      fullPath: '/$countryCode/order/$id/transfer/$token'
      preLoaderRoute: typeof CountryCodeMainOrderIdTransferTokenRouteImport
      parentRoute: typeof CountryCodeMainRoute
    }
    '/$countryCode/_main/order/$id/transfer/$token/': {
      id: '/$countryCode/_main/order/$id/transfer/$token/'
      path: '/'
      fullPath: '/$countryCode/order/$id/transfer/$token/'
      preLoaderRoute: typeof CountryCodeMainOrderIdTransferTokenIndexRouteImport
      parentRoute: typeof CountryCodeMainOrderIdTransferTokenRoute
    }
    '/$countryCode/_main/order/$id/transfer/$token/accept': {
      id: '/$countryCode/_main/order/$id/transfer/$token/accept'
      path: '/accept'
      fullPath: '/$countryCode/order/$id/transfer/$token/accept'
      preLoaderRoute: typeof CountryCodeMainOrderIdTransferTokenAcceptRouteImport
      parentRoute: typeof CountryCodeMainOrderIdTransferTokenRoute
    }
    '/$countryCode/_main/order/$id/transfer/$token/decline': {
      id: '/$countryCode/_main/order/$id/transfer/$token/decline'
      path: '/decline'
      fullPath: '/$countryCode/order/$id/transfer/$token/decline'
      preLoaderRoute: typeof CountryCodeMainOrderIdTransferTokenDeclineRouteImport
      parentRoute: typeof CountryCodeMainOrderIdTransferTokenRoute
    }
  }
}

interface CountryCodeCheckoutRouteChildren {
  CountryCodeCheckoutCheckoutRoute: typeof CountryCodeCheckoutCheckoutRoute
}

const CountryCodeCheckoutRouteChildren: CountryCodeCheckoutRouteChildren = {
  CountryCodeCheckoutCheckoutRoute: CountryCodeCheckoutCheckoutRoute,
}

const CountryCodeCheckoutRouteWithChildren =
  CountryCodeCheckoutRoute._addFileChildren(CountryCodeCheckoutRouteChildren)

interface CountryCodeMainAccountOrdersRouteChildren {
  CountryCodeMainAccountOrdersDetailsIdRoute: typeof CountryCodeMainAccountOrdersDetailsIdRoute
}

const CountryCodeMainAccountOrdersRouteChildren: CountryCodeMainAccountOrdersRouteChildren =
  {
    CountryCodeMainAccountOrdersDetailsIdRoute:
      CountryCodeMainAccountOrdersDetailsIdRoute,
  }

const CountryCodeMainAccountOrdersRouteWithChildren =
  CountryCodeMainAccountOrdersRoute._addFileChildren(
    CountryCodeMainAccountOrdersRouteChildren,
  )

interface CountryCodeMainAccountRouteChildren {
  CountryCodeMainAccountAddressesRoute: typeof CountryCodeMainAccountAddressesRoute
  CountryCodeMainAccountOrdersRoute: typeof CountryCodeMainAccountOrdersRouteWithChildren
  CountryCodeMainAccountProfileRoute: typeof CountryCodeMainAccountProfileRoute
  CountryCodeMainAccountIndexRoute: typeof CountryCodeMainAccountIndexRoute
}

const CountryCodeMainAccountRouteChildren: CountryCodeMainAccountRouteChildren =
  {
    CountryCodeMainAccountAddressesRoute: CountryCodeMainAccountAddressesRoute,
    CountryCodeMainAccountOrdersRoute:
      CountryCodeMainAccountOrdersRouteWithChildren,
    CountryCodeMainAccountProfileRoute: CountryCodeMainAccountProfileRoute,
    CountryCodeMainAccountIndexRoute: CountryCodeMainAccountIndexRoute,
  }

const CountryCodeMainAccountRouteWithChildren =
  CountryCodeMainAccountRoute._addFileChildren(
    CountryCodeMainAccountRouteChildren,
  )

interface CountryCodeMainOrderIdTransferTokenRouteChildren {
  CountryCodeMainOrderIdTransferTokenAcceptRoute: typeof CountryCodeMainOrderIdTransferTokenAcceptRoute
  CountryCodeMainOrderIdTransferTokenDeclineRoute: typeof CountryCodeMainOrderIdTransferTokenDeclineRoute
  CountryCodeMainOrderIdTransferTokenIndexRoute: typeof CountryCodeMainOrderIdTransferTokenIndexRoute
}

const CountryCodeMainOrderIdTransferTokenRouteChildren: CountryCodeMainOrderIdTransferTokenRouteChildren =
  {
    CountryCodeMainOrderIdTransferTokenAcceptRoute:
      CountryCodeMainOrderIdTransferTokenAcceptRoute,
    CountryCodeMainOrderIdTransferTokenDeclineRoute:
      CountryCodeMainOrderIdTransferTokenDeclineRoute,
    CountryCodeMainOrderIdTransferTokenIndexRoute:
      CountryCodeMainOrderIdTransferTokenIndexRoute,
  }

const CountryCodeMainOrderIdTransferTokenRouteWithChildren =
  CountryCodeMainOrderIdTransferTokenRoute._addFileChildren(
    CountryCodeMainOrderIdTransferTokenRouteChildren,
  )

interface CountryCodeMainRouteChildren {
  CountryCodeMainAccountRoute: typeof CountryCodeMainAccountRouteWithChildren
  CountryCodeMainCartRoute: typeof CountryCodeMainCartRoute
  CountryCodeMainStoreRoute: typeof CountryCodeMainStoreRoute
  CountryCodeMainVerifyAccountRoute: typeof CountryCodeMainVerifyAccountRoute
  CountryCodeMainIndexRoute: typeof CountryCodeMainIndexRoute
  CountryCodeMainCategoriesSplatRoute: typeof CountryCodeMainCategoriesSplatRoute
  CountryCodeMainCollectionsHandleRoute: typeof CountryCodeMainCollectionsHandleRoute
  CountryCodeMainProductsHandleRoute: typeof CountryCodeMainProductsHandleRoute
  CountryCodeMainOrderIdConfirmedRoute: typeof CountryCodeMainOrderIdConfirmedRoute
  CountryCodeMainOrderIdTransferTokenRoute: typeof CountryCodeMainOrderIdTransferTokenRouteWithChildren
}

const CountryCodeMainRouteChildren: CountryCodeMainRouteChildren = {
  CountryCodeMainAccountRoute: CountryCodeMainAccountRouteWithChildren,
  CountryCodeMainCartRoute: CountryCodeMainCartRoute,
  CountryCodeMainStoreRoute: CountryCodeMainStoreRoute,
  CountryCodeMainVerifyAccountRoute: CountryCodeMainVerifyAccountRoute,
  CountryCodeMainIndexRoute: CountryCodeMainIndexRoute,
  CountryCodeMainCategoriesSplatRoute: CountryCodeMainCategoriesSplatRoute,
  CountryCodeMainCollectionsHandleRoute: CountryCodeMainCollectionsHandleRoute,
  CountryCodeMainProductsHandleRoute: CountryCodeMainProductsHandleRoute,
  CountryCodeMainOrderIdConfirmedRoute: CountryCodeMainOrderIdConfirmedRoute,
  CountryCodeMainOrderIdTransferTokenRoute:
    CountryCodeMainOrderIdTransferTokenRouteWithChildren,
}

const CountryCodeMainRouteWithChildren = CountryCodeMainRoute._addFileChildren(
  CountryCodeMainRouteChildren,
)

interface CountryCodeRouteChildren {
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRouteWithChildren
  CountryCodeMainRoute: typeof CountryCodeMainRouteWithChildren
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeCheckoutRoute: CountryCodeCheckoutRouteWithChildren,
  CountryCodeMainRoute: CountryCodeMainRouteWithChildren,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
